version: 2.1
workflows:
  main:
    jobs:
      - test-functions
jobs:
  test-functions:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run lint
      - run: echo ${ENV} > ~/.env
      - run: echo 'npm run test'
