version: 2.1
workflows:
  main:
    jobs:
      - hello
      - poyo
      - test-functions:
          requires:
            - hello
            - poyo
      - build_and_deploy:
          requires:
            - test-functions

jobs:
  hello:
    machine: true
    steps:
      - run:
          name: Hello
          command: echo 'hello'

  poyo:
    machine: true
    steps:
      - run:
          name: Poyo
          command: echo 'poyo'

  test-functions:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "increase-of-kirby/package.json" }}
            - v1-dependencies-
      - run: cd increase-of-kirby; npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "increase-of-kirby/package.json" }}
      - run: cd increase-of-kirby; echo ${ENV} > ~/.env
      - run: cd increase-of-kirby; npm run lint
      - run: cd increase-of-kirby; echo 'npm run test'

  build_and_deploy:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - run: cd increase-of-kirby; npm install
      - run: cd increase-of-kirby; echo ${ENV} > ~/.env
      - run: cd increase-of-kirby; npm run build
      - run: cd increase-of-kirby; echo 'deployしたい'
